apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uat-dmb

resources:
  - ../../base

patches:
  - path: patch-app-deployment.yaml

images:
  - name: keanghor/devconnect-api-img
    newTag: "latest"   