apiVersion: apps/v1
kind: Deployment
metadata:
  name: devconnect-app
  labels:
    app: devconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devconnect
  template:
    metadata:
      labels:
        app: devconnect
    spec:
      containers:             # ✅ ត្រូវ indent នៅក្រោម spec:
        - name: devconnect
          image: keanghor/devconnect-api-img:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: devconnect-config
            - secretRef:
                name: devconnect-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5