apiVersion: v1
kind: ConfigMap
metadata:
  name: devconnect-config
data:
  # Application
  SPRING_APPLICATION_NAME: "DevConnect_SpringBoot"
  SPRING_MAIN_BANNER_MODE: "off"
  LOGGING_LEVEL_ROOT: "info"                              # ✅ ពី warn → info

  # Datasource
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/railway"

  # Redis
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_CACHE_TYPE: "redis"

  # MinIO
  MINIO_URL: "http://minio:9000"
  MINIO_BUCKET_NAME: "devconnect"

  # Mail
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: "devconnectfromfuture@gmail.com"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"

  # Sentry
  SENTRY_DSN: "https://30dfbdaddd85d3e5817d36ab132ce0d9@o4507411174326272.ingest.us.sentry.io/4510712203378688"
  SENTRY_TRACES_SAMPLE_RATE: "1.0"

  # JPA
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"