apiVersion: v1
kind: Secret
metadata:
  name: devconnect-secret
type: Opaque
stringData:
  # Datasource (Spring App)
  SPRING_DATASOURCE_USERNAME: "postgres-admin"
  SPRING_DATASOURCE_PASSWORD: "ZmWBjVkDkWAnoBfxIAtqhcXcLMPzuWfM"

  # MinIO (Spring App)
  MINIO_ACCESS_NAME: "JfSKDNNhoF5Yz0f4WrpK"
  MINIO_ACCESS_SECRET: "GIJsCv5COUCTrlxQK8zAhb8BmTOdaLeIzGnrsfCJ"

  # Mail (Spring App)
  SPRING_MAIL_PASSWORD: "zqxrsavpbwevbegf"

  # ✅ បន្ថែម — PostgreSQL container init
  POSTGRES_DB: "railway"
  POSTGRES_USER: "postgres-admin"
  POSTGRES_PASSWORD: "ZmWBjVkDkWAnoBfxIAtqhcXcLMPzuWfM"

  # ✅ បន្ថែម — MinIO container init
  MINIO_ROOT_USER: "JfSKDNNhoF5Yz0f4WrpK"
  MINIO_ROOT_PASSWORD: "GIJsCv5COUCTrlxQK8zAhb8BmTOdaLeIzGnrsfCJ"