apiVersion: v1
kind: Secret
metadata:
  name: devconnect-secret
type: Opaque
stringData:
  # Spring App — Datasource
  SPRING_DATASOURCE_USERNAME: "postgres-admin"
  SPRING_DATASOURCE_PASSWORD: "ZmWBjVkDkWAnoBfxIAtqhcXcLMPzuWfM"

  # Spring App — MinIO
  MINIO_ACCESS_NAME: "JfSKDNNhoF5Yz0f4WrpK"
  MINIO_ACCESS_SECRET: "GIJsCv5COUCTrlxQK8zAhb8BmTOdaLeIzGnrsfCJ"

  # Spring App — Mail
  SPRING_MAIL_PASSWORD: "zqxrsavpbwevbegf"

  # PostgreSQL container init keys
  POSTGRES_DB: "railway"
  POSTGRES_USER: "postgres-admin"
  POSTGRES_PASSWORD: "ZmWBjVkDkWAnoBfxIAtqhcXcLMPzuWfM"

  # MinIO container init keys
  MINIO_ROOT_USER: "JfSKDNNhoF5Yz0f4WrpK"
  MINIO_ROOT_PASSWORD: "GIJsCv5COUCTrlxQK8zAhb8BmTOdaLeIzGnrsfCJ"